Mortal\DumplingBundle\Entity\Email:
    type: entity
    table: email_list
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        email:
            type: string
            length: 255
    lifecycleCallbacks: {  }
