parameters:
#    mortal_dumpling.example.class: Mortal\DumplingBundle\Example

services:
#    mortal_dumpling.example:
#        class: %mortal_dumpling.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
